apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix-relay
  template:
    metadata:
      labels:
        app: postfix-relay
    spec:
      containers:
      - name: postfix
        image: ghcr.io/chilledether/postfix:latest
        env:
        - name: RELAYHOST
          value: "smtp.relay.example.com:587"
        - name: RELAYHOST_USERNAME
          value: "my-relay-username"
        - name: RELAYHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postfix-sasl-secret
              key: RELAYHOST_PASSWORD
        - name: ALLOWED_SENDER_DOMAINS
          value: "example.com example.org"
        - name: POSTFIX_smtp_tls_security_level
          value: encrypt
